### ISSUE TITLE
bundle extension

### ISSUE THREAD

**Issue by stphnlyd** [P403n1x87/austin-vscode#17] opened 2021-10-26 15:41 UTC
Now the built extension has >1.6k files, most of them are js files. Could be good to bundle the js files. See 
https://code.visualstudio.com/api/working-with-extensions/bundling-extension

**Comment by P403n1x87** [comment] 2022-10-21 10:14
@stphnlyd I have tried bundling as described in the docs but I think it helped up to a point. I think the main issue is caused by d3, but my node experience is very limited. I'm more than happy to get help/suggestions/tips to further improve on this. I'm closing this for now, but if there is more that can be done we can re-open.

**Closed by P403n1x87** 2022-10-21 10:14 UTC
