### ISSUE TITLE
Code 33

### ISSUE THREAD

**Issue by ayush22jain** [P403n1x87/austin-vscode#64] opened 2024-06-21 13:26 UTC
Running the Austin extension on Windows and it just doesn’t seem to work - I keep getting the error message “Austin process exited with code 33” “the terminal process terminated with exit code:33” “terminal will be reused by tasks, press any key to close it”

When I try to pipe it using powershell, however, it works and gives me a .austin file as the output. But when I try to open the file using the flamegraph tab, it says “crunching the numbers” for a long time and eventually exits. I also get nothing displayed on Austin Stats

**Comment by P403n1x87** [comment] 2024-06-22 08:36
👋  @ayush22jain thanks for reporting this. May I get some more details from you please?

> Running the Austin extension on Windows and it just doesn’t seem to work - I keep getting the error message “Austin process exited with code 33” “the terminal process terminated with exit code:33” “terminal will be reused by tasks, press any key to close it”

How are you running Austin in this case? Is it via a task definition, or the "Profile with Austin" command?

> When I try to pipe it using powershell, however, it works and gives me a .austin file as the output. But when I try to open the file using the flamegraph tab, it says “crunching the numbers” for a long time and eventually exits. I also get nothing displayed on Austin Stats

It might be the case that the file is too big to be processed. If so, you could try increasing the sampling interval with `-i/--interval` to reduce the number of samples collected. That should make the file easier to parse by the extension (at the cost of some accuracy).

**Comment by spaceman1313** [comment] 2024-08-29 16:16
I'm having the same problem with VS Code on Windows.  I have the latest VS Code, just installed the Austin extension as well ast the austin executables.

I have a very simple python script for testing (basically a single time.sleep() command followed by print())

I'm running Austin with "Profile with Austin" <Shift><F5>  command

The path to my python script does have a space in it but the extension seems to be putting in quotes to account for it:

`Starting Profiler in d:\Documents\Files & Data\My_Project\Python.
Running 'austin' with args '-i 100 --pipe P:\programming\anaconda3\carlosn\envs\gcat\python.exe "d:\Documents\Files & Data\My_Project\Python\sleep.py"'.
austin process exited with code 33`

I can run Austin directly from the VS Code terminal and it works fine:
`austin python sleep.py`

**Comment by bemaru** [comment] 2024-09-07 07:50
@ayush22jain 
Have you tried it like this?
`pip install austin-dist`

**Comment by P403n1x87** [comment] 2024-10-20 20:43
This is likely a duplicate of #62

**Closed** 2024-10-20 20:46 UTC
